version: '2.4'

services:
  node:
    container_name: node
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./api
    ports:
      - "5000:5000"
    command:
      - sh
      - "-c"
      - "npm run dev"
    env_file:
      - dev-db.env
    depends_on:
      - couchdb

  couchdb:
    container_name: couchdb
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./db
    ports:
      - "5984:5984"
    env_file:
      - dev-db.env
    volumes:
      - ./db/db_data :/opt/couchdb/data
      - ./db/local.d :/opt/couchdb/etc/local.d

  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./frontend
      target: build
    ports:
      - "3000:3000"
    command:
      - sh
      - "-c"
      - "npm run start"